# Chapter47
## 📌문제1
### 다음 코드의 실행 결과를 서술하시오.
```js
const func = (n, f) => {
  if(typeof f !== 'function') new Error('f must be function');
  f(n);
}

try {
  func(1, 2);
}catch(e){
   console.log(e);
}
```
### 정답 및 해설
```
TypeError: f is not a function
error을 throw 하지 않아서 try catch 문에서 에러 처리가 되지 않는다
```

<br>
