# Chapter45
## 📌문제1

### true or false를 판단하세요.

```
(1) 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
(2) settled 상태에서 비동기 처리가 수행 성공되면 resolve 함수를 호출하여 프로미스를 fulfilled 상태로 변경한다.
(3) 에러 처리는 catch 메서드보다 then 메서드의 두 번째 콜백 함수를 사용하는 것이 더 권장된다.
```

### 답안 작성
```
(1) true
(2) false
(3) false
```
```
(1) (843p) 
비동기 함수란 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말합니다.
비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료됩니다.

(2) (851p)
settled 상태는 fulfilled, rejected 상태와 상관없이 pending이 아닌 상태로, 비동기 처리가 수행된 상태를 말합니다.
settled 상태가 되면 더는 다른 상태로 변화할 수 없습니다.

(3) (856p)
then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고
코드가 복잡해져서 가독성이 좋지 않습니다.
또한 then 메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 더 좋고, 명확합니다.
따라서 에러 처리는 then 메서드에서 하지 않고, catch 메서드에서 하는 것을 권장합니다.
```

<br>

## 📌문제2

### 다음 코드 중, catch 코드 블록에서 에러 캐치가 되지 않는 설명하세요.
```js
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 100);
} catch (e) {
    // 에러 캐치X
  console.error("캐치한 에러", e);
}
```

### 답안 작성
```
(849p)
에러는 호출자 방향(콜스택의 아래방향)으로 전파됩니다.
즉 실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향으로 전파됩니다.
하지만 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아닙니다.
따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않습니다.
```

<br>

## 📌문제3
### 다음 코드의 출력 순서를 작성하세요.
```js
setTimeout(() => console.log(1), 0); // (1)

Promise.resolve()
  .then(() => console.log(2)) // (2)
  .then(() => console.log(3)); // (3)
```

### 답안 작성
```
2 -> 3-> 1
```
```
(864p)
프로미스의 후속 처리 메서드는 비동기로 동작하므로 1,2,3 순서로 출력될 것 같은 예상과 달리 2,3,1의 순서로 출력됩니다.
프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라, 마이크태스크 큐에 저장되기 때문입니다.
그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 정지됩니다.
마이크로태스크 큐는 태스크 큐보다 우선순위가 높기 때문에 2,3,1의 순서로 출력됩니다.
```

<br>

